#!/bin/sh
case $SCALA_HOME in
"")  echo SCALA_HOME is not defined ;;
*)   echo Launching VisualLangLab ... ; java -D"java.util.Arrays.useLegacyMergeSort=true" -cp VLLS.jar:$SCALA_HOME/lib/scala-library.jar:$SCALA_HOME/lib/scala-compiler.jar:$SCALA_HOME/lib/scala-swing.jar vll.gui.VllGui ;;
esac
